### PR TITLE
More missing US time zone aliases and correct Mountain Standard Time

### PR DESCRIPTION
**Pull request by vais**
Sorry I didn't catch this problem until after the 1.2 release :(

### CODE REVIEW

**Comment by jmettraux** [comment]
@vais Thanks a lot, I will merge and release 1.2.1.

Do you have a list of those Windows timezones? It seems the ones from https://github.com/floraison/et-orbi/blob/c5b8a669555a994f8b78fe6d0b779cd493543ce1/lib/et-orbi/zones.rb#L244-L246 are incomplete then.

**Comment by vais** [comment]
@jmettraux it's not that they are incomplete, it's more like the approach currently used seems to be fundamentally flawed, unfortunately, - i.e. using `Time#zone` which returns a *human-readable* description of a time zone as a key into the `ZONE_ALIASES` lookup table.

The reason it's flawed is because there does not seem to be any guarantees as to what these time zone descriptions will be on any given machine/windows version/international locale combination. These descriptions are stored in the Windows registry (`HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Time Zones`), and, at least judging by [this](https://docs.microsoft.com/en-us/windows/desktop/api/timezoneapi/ns-timezoneapi-_time_zone_information#remarks), they would even be localized according to the current user default UI language (but I have not actually tried this).

I've only done very limited research on this, and I'm in no way an expert on the subject, but here is what I've got so far: it looks like Ruby on Windows uses ([here](https://github.com/ruby/ruby/blob/trunk/win32/win32.c#L7848)) [GetTimeZoneInformation](https://docs.microsoft.com/en-us/windows/desktop/api/timezoneapi/nf-timezoneapi-gettimezoneinformation) function, which uses the [TIME_ZONE_INFORMATION](https://docs.microsoft.com/en-us/windows/desktop/api/timezoneapi/ns-timezoneapi-_time_zone_information) structure, which brings us to the remarks regarding time zone descriptions being stored in the Windows registry, etc.

**Comment by jmettraux** [comment]
@vais Thanks a ton!

**Comment by vais** [comment]
No, @jmettraux, thank **you** for rufus-scheduler! ❤️

**Pull request merged**
