### PR TITLE
Handle Rails Duration types

### PR DESCRIPTION
**Pull request by d-m-u**
It'd be nice to handle Rails Durations for comparisons here since as it stands, it doesn't support comparisons with user provided Time objects. Could we do something like this, please?

### CODE REVIEW

**Comment by jmettraux** [comment]
Hello, thanks for the contribution.

It's a bit hard to see what you mean by this change. Do you have some context for me?

I'll do my best to adapt et-orbi then.

Thanks in advance,

**Comment by d-m-u** [comment]
Sure, sorry. We've just updated to rufus 3.6 and we're using a gross patch because our tests use ActiveRecord TimeWithZone and et-orbi on this particular line doesn't support comparisons of EoTime with AR objects. 

I think it'd be cool to be able to do something like this with a rufus scheduler: 

```
job = rufus_scheduler.jobs.first
expect(job.next_time).to eq(3.hours.from_now)
```

**Comment by jmettraux** [comment]
meanwhile:

```
job = rufus_scheduler.jobs.first
expect(job.next_time.to_i).to eq(3.hours.from_now.to_i)
```
or
```
job = rufus_scheduler.jobs.first
expect(job.next_time.to_i).to be_within(2).of(3.hours.from_now.to_i)
```

**Comment by d-m-u** [comment]
Yes, but that feels like it shouldn't have to be part of the test itself. Since you're checking for EO types on this line, why not make that as true to Postel's law as possible?

**Comment by jmettraux** [comment]
1. `expect(job.next_time).to eq(3.hours.from_now)` is brittle, it only works 3 hours from now, exactly
2. do you know what stands behind Rspec's `eq`?

**Comment by jmettraux** [comment]
Re-opening. I want to make sure comparison with Time and ActiveSupport Time works.

**Comment by jmettraux** [comment]
Note to self: https://relishapp.com/rspec/rspec-expectations/docs/built-in-matchers/equality-matchers

**Comment by jmettraux** [comment]
Closing and moving to gh-7.

**Comment by jmettraux** [comment]
Hello @d-m-u, would https://github.com/floraison/et-orbi/commit/283f5e207e9a6fe6a50dc2e39fc2e40eebd5b3b5 suit you and your company?

**Comment by jmettraux** [comment]
@d-m-u Just released [et-orbi 1.2.2](https://rubygems.org/gems/et-orbi).

If there is anything wrong, please tell me.

Best regards,

**Comment by d-m-u** [comment]
Thank you!!

**Pull request closed without merging**
